config/routes.rb
DavinciMotors::Application.routes.draw do
  root to: 'cars#index'

  resources :cars

  match '/cars/:id/payments',
        to: 'cars#payments',
        via: [:get, :post, :patch],
        as: 'payment_calculator'

  get '/cars/:id/claim',
      to: 'cars#claim',
      as: 'claim_car'

  resources :users, only: [:new, :create], path_names: { new: "signup"}

  get '/login',
      to: 'sessions#login',
      as: 'login'

  post '/login',
       to: 'sessions#create'

  get '/auth/:provider/callback', to: 'sessions#oauth'

  delete '/logout',
         to: 'sessions#destroy',
         as: 'logout'
end

app/models/student.rb
class Student < ActiveRecord::Base
  def self.seed_data!
    ages = (5..18).to_a
    heights = {
        5 => (40..46).to_a,
        6 => (42..49).to_a,
        7 => (44..52).to_a,
        8 => (47..54).to_a,
        9 => (49..57).to_a,
        10 => (50..59).to_a,
        11 => (52..61).to_a,
        12 => (54..64).to_a,
        13 => (56..66).to_a,
        14 => (59..70).to_a,
        15 => (62..72).to_a,
        16 => (63..73).to_a,
        17 => (64..74).to_a,
        18 => (65..75).to_a,
    }
    500.times do |number|
      age = ages.sample
      date_of_birth = (age).years.ago + rand(11).months + rand(30).days
      height = heights[age].sample
      Student.create(
          :first_name => Faker::Name.first_name,
          :middle_name => Faker::Name.first_name,
          :last_name => Faker::Name.last_name,
          :date_of_birth => date_of_birth,
          :hair_color => ['red', 'brown', 'black', 'blonde'].sample,
          :eye_color => ['blue', 'green', 'brown'].sample,
          :height => height,
          :weight => random_weight_for_height(height),
          :sex => ['M', 'F'].sample
      )
    end
  end

  private

  def self.random_weight_for_height(height)
    bmi = (19..40).to_a.sample
    sprintf("%.2f", ((height * height) * bmi)/703)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password(validations: false)

  has_many :cars

  validates_confirmation_of :password, if: lambda { |m| !m.omniauth? && m.password.present? }
  validates_presence_of :password, :on => :create, if: lambda { |m| !m.omniauth? }
  validates_presence_of :password_confirmation, if: lambda { |m| !m.omniauth? && m.password.present? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue ActiveRecord::RecordNotFound
    session.delete(:user_id)
    redirect_to root_path, alert: "Invalid Username/Password"
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car,
                only: [:show, :edit, :update,
                       :destroy, :payments, :claim,
                       :unclaim]

  def my_cars
    @cars = Car.where(user_id: current_user.id).paginate(page: params[:page])
  end

  def claim
    if current_user
      current_user.cars << @car
      redirect_to root_path, notice: "#{@car.make} #{@car.model} has been moved to your inventory."
    end
  end

  def unclaim
    if current_user && @car.owned_by?(current_user)
      @car.update_attributes(user: nil)
      redirect_to my_cars_path,
        notice: "#{@car.make} #{@car.model} has been removed from your inventory."
    end
  end

  def payments
    if params[:interest_rate].present? && params[:payment_amount].present?
      @payment_calculator = PaymentCalculator.new(@car.price)
    end
  end

  # GET /cars
  # GET /cars.json
  def index
    #sleep 2
    @cars = Car.where(user_id: nil).paginate(page: params[:page])
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to cars_path, notice: "#{@car.year} #{@car.make} #{@car.model} created" }
        format.json { render action: 'show', status: :created, location: @car }
      else
        format.html { render action: 'new' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to cars_path, notice: "#{@car.year} #{@car.make} #{@car.model} updated" }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: "#{@car.year} #{@car.make} #{@car.model} deleted" }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_car
    @car = Car.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def car_params
    params.require(:car).permit(:make, :model, :year, :price)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
  end

  def oauth
    @user = User.where(email: omniauth_options[:email]).first_or_initialize(omniauth_options)
    if @user.persisted?
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Welcome back #{@user.first_name}."
    else
      render 'users/new'
    end
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      # User submitted valid password
      session[:user_id] = user.id
      redirect_to root_path, notice: "Welcome back #{user.first_name}."
    else
      # User does not exist or password was invalid
      flash[:alert] = "Invalid email or password"
      render :login
    end
  end

  def destroy
    if user = current_user
      session[:user_id] = nil
      redirect_to root_path, notice: "#{user.email} has been logged out."
    end
  end

  private
  def omniauth_options
    auth_hash = request.env['omniauth.auth']
    first_name, last_name = auth_hash[:info][:name].split(/\s+/, 2)
    {
        email: auth_hash[:info][:email],
        first_name: first_name,
        last_name: last_name,
        omniauth: true
    }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Thank you for signing up #{@user.first_name}."
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :omniauth)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_cars.html.erb
<%= will_paginate @cars %>

<table class="table table-hover">
  <thead>
  <tr>
    <th>Make</th>
    <th>Model</th>
    <th>Year</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @cars.each do |car| %>
    <tr id="<%= dom_id(car) %>">
      <td><%= car.make %></td>
      <td><%= car.model %></td>
      <td><%= car.year %></td>
      <td>
        <%= number_to_currency(car.price) %>
        (<%= link_to 'Calculate Payment', payment_calculator_path(car) %>)
      </td>
      <td><%= link_to 'Show', car %></td>
      <% if current_user %>
        <td><%= link_to 'Claim', claim_car_path(car) %></td>
      <% end %>
      <td><%= link_to 'Edit', edit_car_path(car) %></td>
      <td><%= link_to 'Delete', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @cars %>

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :make %><br>
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/_loan_payment.html.erb
<tr>
  <td><%= (Date.today + loan_payment.payment_number.months).beginning_of_month %></td>
  <td><%= number_to_currency(loan_payment.payment) %></td>
  <td><%= number_to_currency(loan_payment.principle) %></td>
  <td><%= number_to_currency(loan_payment.interest) %></td>
  <td><%= number_to_currency(loan_payment.balance_after_payment) %></td>
</tr>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<h1>Listing cars</h1>

<div class="cars_loading">
  <%= image_tag('ajax_load.gif') %>
</div>

<div class="cars">
  <%= render :partial => 'cars' %>
</div>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/my_cars.html.erb
<h1>My Cars</h1>

<div class="cars_loading">
  <%= image_tag('ajax_load.gif') %>
</div>

<div class="cars">
  <%= render :partial => 'cars' %>
</div>

<br>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/payment.html.erb
<h1>Payment Calculator</h1>

<div class="jumbotron">
  <%= form_for @car, url: payment_calculator_path(@car), html: {class: 'form-horizontal', role: 'form'} do |f| %>
      <div class="form-group">
        <%= label_tag 'make', 'Make', class: 'col-md-4 control-label' %>
        <div class="col-md-8">
          <%= text_field_tag 'make', @car.make, disabled: true %>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag 'model', 'Model', class: 'col-md-4 control-label' %>
        <div class="col-md-8">
          <%= text_field_tag 'model', @car.model, disabled: true %>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag 'year', 'Year', class: 'col-md-4 control-label' %>
        <div class="col-md-8">
          <%= text_field_tag 'year', @car.year, disabled: true %>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag 'price', 'Price', class: 'col-md-4 control-label' %>
        <div class="col-md-8">
          <%= text_field_tag 'price', number_to_currency(@car.price), disabled: true %>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag 'interest_rate', 'Interest Rate', class: 'col-md-4 control-label' %>
        <div class="col-md-8">
          <%= text_field_tag 'interest_rate', params[:interest_rate] %>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag 'payment_amount', 'Payment Amount', class: 'col-md-4 control-label' %>
        <div class="col-md-8">
          <%= text_field_tag 'payment_amount', params[:payment_amount] %>
        </div>
      </div>
      <div class="actions">

      </div>
      <div class="form-group">
        <div class="col-md-offset-4 col-md-8">
          <%= f.submit 'Calculate', class: "btn btn-success" %>
        </div>
      </div>
  <% end %>

</div>

<% if @payment_calculator %>
    <table id="payments" class="table table-hover">
      <tr>
        <th>Date</th>
        <th>Payment</th>
        <th>Principle</th>
        <th>Interest</th>
        <th>New Balance</th>
      </tr>
      <tr>
        <td><%= Date.today %></td>
        <td colspan="3">&nbsp;</td>
        <td><%= number_to_currency(@payment_calculator.total_owed) %></td>
      </tr>
      <%= render :partial => 'loan_payment',
                 :collection => @payment_calculator.payments(params[:interest_rate].to_f, params[:payment_amount].to_i) %>
    </table>
<% end %>

app/views/cars/payments.html.erb
<h1>Payment Calculator</h1>

<div class="jumbotron">
  <%= form_for @car, url: payment_calculator_path(@car), html: {class: 'form-horizontal', role: 'form'} do |f| %>
    <div class="form-group">
      <%= label_tag 'make', 'Make', class: 'col-md-4 control-label' %>
      <div class="col-md-8">
        <%= text_field_tag 'make', @car.make, disabled: true %>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag 'model', 'Model', class: 'col-md-4 control-label' %>
      <div class="col-md-8">
        <%= text_field_tag 'model', @car.model, disabled: true %>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag 'year', 'Year', class: 'col-md-4 control-label' %>
      <div class="col-md-8">
        <%= text_field_tag 'year', @car.year, disabled: true %>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag 'price', 'Price', class: 'col-md-4 control-label' %>
      <div class="col-md-8">
        <%= text_field_tag 'price', number_to_currency(@car.price), disabled: true %>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag 'interest_rate', 'Interest Rate', class: 'col-md-4 control-label' %>
      <div class="col-md-8">
        <%= text_field_tag 'interest_rate', params[:interest_rate] %>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag 'payment_amount', 'Payment Amount', class: 'col-md-4 control-label' %>
      <div class="col-md-8">
        <%= text_field_tag 'payment_amount', params[:payment_amount] %>
      </div>
    </div>
    <div class="actions">

    </div>
    <div class="form-group">
      <div class="col-md-offset-4 col-md-8">
        <%= f.submit 'Calculate', class: "btn btn-success" %>
      </div>
    </div>
  <% end %>

</div>

<% if @payment_calculator %>
  <table id="payments" class="table table-hover">
    <tr>
      <th>Date</th>
      <th>Payment</th>
      <th>Principle</th>
      <th>Interest</th>
      <th>New Balance</th>
    </tr>
    <tr>
      <td><%= Date.today %></td>
      <td colspan="3">&nbsp;</td>
      <td><%= number_to_currency(@payment_calculator.total_owed) %></td>
    </tr>
    <%= render :partial => 'loan_payment',
               :collection => @payment_calculator.payments(params[:interest_rate].to_f, params[:payment_amount].to_i) %>
  </table>
<% end %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Make:</strong>
  <%= @car.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @car.year %>
</p>

<p>
  <strong>Price:</strong>
  <%= @car.price %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>